### ISSUE TITLE
message appearing after login

### ISSUE THREAD

**Issue by thoughtpatterns** [rickysarraf/laptop-mode-tools#208]
**Describe the bug**
Booting on runit system places message on login prompt. This is purely cosmetic and does not impact login or functionality.

**To Reproduce**
1. Install "laptop-mode" on Void Linux
2. Boot the system (I am using GRUB with LUKS1 encryption) with laptop plugged into AC
3. A message will appear by username prompt: "enabled, not active [unchanged]"

**Expected behavior**
This message appears before the prompt, rather than during.

**Screenshots**

![p50prompt](https://github.com/rickysarraf/laptop-mode-tools/assets/128649563/322cf271-54e6-4423-a4a5-56182a303cb9)

**Important Information:**
 - Distribution: Void Linux
 - Linux Kernel: 6.6.16_1
 - Laptop Mode Tools version: 1.73.1_2
 - Desktop Environment, if any: bspwm
 - Relevant System Logs: None, as far as I can tell.
 - Laptop Mode Tools verbose logs:
[laptop_mode_logs.txt](https://github.com/rickysarraf/laptop-mode-tools/files/14317865/laptop_mode_logs.txt)

**Additional context**
[The prompt is coming from here, I believe (as pointed out to me by someone else!)](https://github.com/rickysarraf/laptop-mode-tools/blob/b5eefe0b01a16b52365484595643ab177508e76f/usr/sbin/laptop_mode#L1199) The prompt isn't erroneous, I'm just wondering how to change the laptop_mode service to not trigger simultaneously with login (which I believe it is, because I have my tty set to clear before login), if at all possible

**Comment by rickysarraf** [comment]
Hello @moeishome 

>I'm just wondering how to change the laptop_mode service to not trigger simultaneously with login

Laptop Mode Tools (LMT) is invoked via multiple means. The important bit is that whether the service is enabled in `/etc/laptop-mode/laptop-mode.conf`

It is invoked via:
* init (sysvinit, systemd)
* udev
* acpid daemon, if available

The message that you are seeing is possibly by your init manager and/or udev. I can't tell for sure until this is investigated. What I can say for sure that on my system (Debian + systemd) those messages do not show up. But then, that is because we tell systemd to use the journal for LMT's stdout and stderr.

```
rrs@priyasi:~$ systemctl cat laptop-mode
# /usr/lib/systemd/system/laptop-mode.service
[Unit]
Description=Laptop Mode Tools
Documentation=man:laptop_mode(8) man:laptop-mode.conf(8)
Documentation=http://github.com/rickysarraf/laptop-mode-tools

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/bin/rm -f /var/run/laptop-mode-tools/enabled
ExecStartPre=/bin/rm -f /var/run/laptop-mode-tools/state
ExecStart=/usr/sbin/laptop_mode init force
ExecStop=/usr/sbin/laptop_mode init stop
ExecStopPost=/bin/rm -f /var/run/laptop-mode-tools/enabled
ExecStopPost=/bin/rm -f /var/run/laptop-mode-tools/state
ExecReload=/usr/sbin/laptop_mode auto
StandardOutput=journal
StandardError=journal
TasksMax=infinity

[Install]
WantedBy=multi-user.target
```

Perhaps a similar setting may be needed in your setup/init

**Comment by thoughtpatterns** [comment]
Interesting! Thanks so much for your response. I'll take a look and find how to disable something like that in runit, and I appreciate the example as well. As this is something on my end I will close this and update the issue with how I fixed it if/when I figure it out. Thank you for making laptop mode!!!

**Comment by moeishome** [comment]
i ended up just commenting out lines 1193-1200 in the executable until i figure out something else and its working for now! i know runit allows for environment variables to be changed for services; having an if clause for if a QUIET var is set in the conf file of the service would allow disabling on runit systems, id think? thanks for your help.

**Comment by rickysarraf** [comment]
Oh!! I didn't know that Github is losing messages as well. I have an email notification for a comment from you @moeishome but the same doesn't reflect on this issue here.

@moeishome About the `QUIET` feature flag, nobody ever asked for. But it is easy to do. I'd like you to contribute via a PR here. Just look into the `log()` function and extend it for `quiet` mode as well.

**Comment by thoughtpatterns** [comment]
sure! sorry, its been a minute. when i get a chance i will definitely look into this; in the meantime ive just piped the output of the runit "run" file into /dev/null and i figure theres a more elegant way to manage that. bit hectic right now but will do this! thanks for the invitation, much appreciated.
